version: "3.5"

services:
  frontend:
    restart: always
    build: ./frontend
    ports:
     - "4200:4200"
  
  backend:
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://database:27017/newsapp

  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
